name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/contributors-list@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          readme-path: 'README.md'
          marker: '## Contributors'
