name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Generate contributors list
        run: npx all-contributors-cli generate

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md .all-contributorsrc'
          message: 'docs: update contributors [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
